# Allwinner H733
LINUXFAMILY="sun60iw2"
BOARD_NAME="ArmSom-sige6"
UBOOT_CONFIG="lubancat_a1_defconfig"
LINUX_CONFIG="linux_h618_defconfig"
LINUX_DTB_NAME="sun50iw9-lubancat-a1"
# KERNEL_TARGET="current,next"
KERNEL_TARGET="current"
MODULES_CURRENT="aic8800_bsp aic8800_fdrv aic8800_btlpm"
MODULES_NEXT="uaic8800_bsp aic8800_fdrv aic8800_btlpm"
DISTRIB_TYPE_CURRENT="bullseye jammy"
DISTRIB_TYPE_NEXT="bullseye bookworm jammy"
REVISION="1.$(date +%g%m)stable"